In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv('Social_Network_Ads.csv')

In [3]:
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
df1=df.iloc[:,1:]

In [5]:
df1.head()

Gender  Age  EstimatedSalary  Purchased
0    Male   19            19000          0
1    Male   35            20000          0
2  Female   26            43000          0
3  Female   27            57000          0
4    Male   19            76000          0

In [10]:
df2.describe()

Age  EstimatedSalary   Purchased
count  380.000000       380.000000  380.000000
mean    37.586842     70421.052632    0.368421
std     10.592492     34604.155483    0.483012
min     18.000000     15000.000000    0.000000
25%     29.000000     43000.000000    0.000000
50%     37.000000     70500.000000    0.000000
75%     46.000000     88000.000000    1.000000
max     60.000000    150000.000000    1.000000

In [11]:
df2.shape

(380, 4)

In [12]:
df1.isnull().sum()

Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [13]:
df1.duplicated().sum()

np.int64(20)

In [14]:
df2=df1.drop_duplicates()

In [15]:
df2.duplicated().sum()

np.int64(0)

In [29]:
x=df2.iloc[:,:3]
y=df2[['Purchased']]

In [30]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [31]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,StandardScaler

In [32]:
trans=ColumnTransformer(transformers=[
    ('tnf1',OneHotEncoder(sparse_output=False,drop="first"),['Gender']),
    ('tnf2',StandardScaler(),['Age','EstimatedSalary'])
],remainder='passthrough')                 
                       

In [33]:
trans

ColumnTransformer(remainder='passthrough',
                  transformers=[('tnf1',
                                 OneHotEncoder(drop='first',
                                               sparse_output=False),
                                 ['Gender']),
                                ('tnf2', StandardScaler(),
                                 ['Age', 'EstimatedSalary'])])

In [34]:
x_train

Gender  Age  EstimatedSalary
78   Female   28            87000
224  Female   35            60000
305    Male   42            54000
115    Male   40            57000
207  Female   52           114000
..      ...  ...              ...
71   Female   24            27000
108    Male   26            86000
278  Female   52            38000
363  Female   42            79000
104  Female   19            21000

[304 rows x 3 columns]

In [37]:
x_train_transformed=trans.fit_transform(x_train)
x_train_transformed

array([[ 0.        , -0.90071374,  0.50506469],
       [ 0.        , -0.23100066, -0.30146663],
       [ 1.        ,  0.43871242, -0.48069581],
       [ 1.        ,  0.24736583, -0.39108122],
       [ 0.        ,  1.39544539,  1.311596  ],
       [ 1.        , -0.23100066,  0.14660632],
       [ 0.        ,  0.43871242,  0.29596398],
       [ 0.        ,  2.16083176, -0.71966805],
       [ 0.        ,  0.9170789 ,  1.28172447],
       [ 1.        , -1.8574467 , -0.54043887],
       [ 0.        , -0.23100066, -0.77941111],
       [ 1.        , -0.03965406, -0.54043887],
       [ 1.        ,  0.9170789 , -1.34697018],
       [ 1.        , -1.28340692, -1.52619936],
       [ 0.        , -1.8574467 , -0.06249439],
       [ 0.        , -0.51802055,  2.38697108],
       [ 1.        , -1.18773363, -1.43658477],
       [ 0.        , -0.03965406,  0.29596398],
       [ 1.        ,  0.15169253,  0.20634938],
       [ 1.        ,  0.15169253,  0.0271202 ],
       [ 0.        , -0.03965406,  0.027

In [38]:
x_test_transformed=trans.transform(x_test)
x_test_transformed

array([[ 0.        ,  1.87381187, -1.31709865],
       [ 1.        ,  0.24736583, -0.2715951 ],
       [ 1.        ,  0.15169253,  1.07262376],
       [ 0.        , -0.99638703, -1.167741  ],
       [ 0.        , -0.90071374, -0.77941111],
       [ 1.        ,  0.43871242, -0.18198051],
       [ 0.        , -1.28340692, -0.45082428],
       [ 0.        ,  0.53438572,  1.87915507],
       [ 0.        ,  1.39544539,  2.02851272],
       [ 1.        , -1.57042681,  0.53493622],
       [ 1.        ,  0.43871242,  2.35709955],
       [ 1.        , -0.03965406,  0.20634938],
       [ 1.        , -0.70936714,  0.56480775],
       [ 0.        ,  1.96948517,  0.74403693],
       [ 1.        ,  0.24736583, -0.33133816],
       [ 0.        ,  0.82140561, -1.13786947],
       [ 1.        ,  0.34303912, -0.54043887],
       [ 0.        , -1.37908022, -0.65992499],
       [ 0.        ,  0.82140561,  0.35570704],
       [ 0.        , -0.70936714,  1.37133906],
       [ 1.        , -0.80504044,  0.295

In [39]:
from sklearn.svm import SVC

In [93]:
model=SVC(C=5.0,kernel='poly',degree=3)

In [94]:
model.fit(x_train_transformed,y_train)

C:\Users\keerthi\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(C=5.0, kernel='poly')

In [95]:
y_pred=model.predict(x_train_transformed)
y_pred

array([0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,

In [96]:
y_pred1=model.predict(x_test_transformed)
y_pred1

array([1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 0])

In [97]:
from sklearn.metrics import accuracy_score

In [98]:
accuracy_score(y_pred,y_train)

0.8848684210526315

In [99]:
accuracy_score(y_pred1,y_test)

0.9078947368421053

In [100]:
from sklearn.linear_model import LogisticRegression
mo=LogisticRegression()

In [101]:
mo.fit(x_train_transformed,y_train)

C:\Users\keerthi\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [102]:
y_pred2=mo.predict(x_test_transformed)
y_pred2

array([1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 1, 0, 0])

In [103]:
accuracy_score(y_pred2,y_test)

0.8026315789473685